[package]
name = "AdnanKhan-ak47"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
hex = "0.4.3"
once_cell = "1.21.3"
reqwest = {version = "0.12.15", features = ["blocking", "json"]}
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10.9"
xmltree = "0.11.0"

