name: Daily Rust Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 18 * * *"  # every day at 18:30 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --release

      - name: Run project (e.g. generate/update files)
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: cargo run --release

      - name: Check for changes
        run: |
          git add .
          if git diff --cached --exit-code; then
            echo "No changes to commit"
            exit 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions-bot@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          git commit -m "Auto-update from GitHub Actions"
          git push origin main || echo "Push failed - maybe no changes?"
